// Code generated by sdk-factory (scripts/generate.sh); DO NOT EDIT.
//
// Behaviour is declared in manifest/sdk.yaml and rendered through
// languages/go/templates/version.mustache. Edit those and regenerate —
// changes made here are lost on the next run and never reach the other SDKs.

package loginradius

// Version is the semver of the v12 SDK release. Stamped into the User-Agent
// header on every outgoing request. Set from manifest/sdk.yaml `sdkVersion`,
// so every LoginRadius SDK reports the same number.
const Version = "12.0.0-rc.1"
